# Common configuration shared between all applications
configserver:
  name: FETEC Cloud Config
  status: Connected to the JHipster Registry running in Kubernetes

jhipster:
  security:
    authentication:
      jwt:
        secret: my-secret-key-which-should-be-changed-in-production-and-be-base64-encoded

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@jhipster-registry:8761/eureka/
