spring:
  cloud:
    circuitbreaker:
      hystrix:
        enabled: false
    loadbalancer:
      ribbon:
        enabled: false
    config:
      # fail-fast: false
      request-read-timeout: 60000
      request-connect-timeout: 30000

zuul:
  host:
    connect-timeout-millis: 35000
    socket-timeout-millis: 60000
    max-per-route-connections: 100
    max-total-connections: 500
  semaphore:
    max-semaphores: 200
  ribbon:
    eager-load:
      enabled: false
  ribbon-isolation-strategy: SEMAPHORE
hystrix:
  metrics:
    enabled: false
    # polling-interval-ms: 
  command:
    default:
      circuitBreaker:
        enabled: false
        # errorThresholdPercentage: 50
      fallback:
        enabled: true
      execution:
        timeout:
          enabled: true
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 120000
          semaphore:
            maxConcurrentRequests: 100
ribbon:
  eager-load:
    enabled: false
  ReadTimeout: 60000
  ConnectTimeout: 3000
  SocketTimeout: 10000